# on:
#   push:
#     branches:
#       - master
# name: ğŸš€ Deploy website on push
# jobs:
#   FTP-Deploy-Action:
#     name: FTP-Deploy-Action     # JOBã®åå‰
#     runs-on: ubuntu-latest      # ä»®æƒ³ç’°å¢ƒã®ç¨®é¡ã‚’æŒ‡å®š
#     steps:
#       - uses: actions/checkout@master
#       - name: FTP-Deploy-Action
#         uses: SamKirkland/FTP-Deploy-Action@2.0.0
#         env:
#           FTP_SERVER: ${{ secrets.FTP_SERVER }}
#           FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#           LOCAL_DIR: ./
#           REMOTE_DIR: "/home/engineer-dhn/www"
